Repository UQComputingSociety/uqcsbot-discord, pull requests merged in 2023-07, with the labels that each got.

#128 Added dominos coupons command
  uqcsbot/__main__.py
  uqcsbot/dominos_coupons.py
Labels: enhancement

#131 Added managecogs command
  uqcsbot/__main__.py
  uqcsbot/manage_cogs.py
Labels: enhancement

#129 Added /pastexams
  uqcsbot/__main__.py
  uqcsbot/past_exams.py
  uqcsbot/utils/uq_course_utils.py
Labels: enhancement

#117 Add morse command
  .gitignore
  uqcsbot/__main__.py
  uqcsbot/morse.py
Labels: enhancement

#125 Added semester, campus and mode options to /whatsdue
  pyproject.toml
  uqcsbot/utils/uq_course_utils.py
  uqcsbot/whatsdue.py
Labels: bug, enhancement

#119 Fix admin/committee ping permissions, fix timezone issues
  uqcsbot/remindme.py
Labels: bug

#127 Made haiku detection non-deterministic
  poetry.lock
  pyproject.toml
  tests/test_haiku.py
  uqcsbot/haiku.py
  uqcsbot/static/syllable_rules.yaml
Labels: enhancement

#133 use cache for both poetry workflow runs
  .github/workflows/run-black.yml
  .github/workflows/run-tests.yml
  .github/workflows/setup-python/action.yml
  .github/workflows/tests.yml
  .github/workflows/typecheck.yml
Labels: enhancement
