Repository UQComputingSociety/uqcsbot-discord, pull requests merged in 2025-03, with the labels that each got.

#216 Adds Alfred
  uqcsbot/__main__.py
  uqcsbot/alfred.py
Labels: new-command

#217 Alfred cmd changes
  uqcsbot/alfred.py
Labels: enhancement

#210 Added more documentation for the yelling decorator
  uqcsbot/minecraft.py
  uqcsbot/voteythumbs.py
  uqcsbot/whatsdue.py
  uqcsbot/yelling.py
Labels: documentation
